### ISSUE TITLE
how to use?

### ISSUE THREAD

**Issue by L-O-G-A-N** [thurdev/roblox-limiteds-sniper-free#1]
title pls

**Comment by thurdev** [comment]
Install tampermonkey:

https://chrome.google.com/webstore/detail/tampermonkey/dhdgffkkebhmkfjojejmpbldmpobfkfo

Then install the code by using the gist:

https://gist.github.com/thurdev/fe1becf9cc81df616c1ad4ddd75bb19f

Just click the raw button on the right side after installing the extension:
<img width="999" alt="Screenshot 2023-04-08 at 20 05 51" src="https://user-images.githubusercontent.com/34294813/230738595-303207bb-4a71-443e-92d2-c4b64744cee0.png">

**Comment by sansan3d** [comment]
is this safe?

**Comment by thurdev** [comment]
It emulates clicks on the page, so I guess yes 👍
