### ISSUE TITLE
Not Buying Anything

### ISSUE THREAD

**Issue by CustomAmelia** [thurdev/roblox-limiteds-sniper-free#12]
sniper doesnt work for me atm, doesn't buy anything or detects anything, heres my env:

```
ROBLOX_COOKIES = GuestData=UserID=-1513173916; domain=.roblox.com; expires=Sun, 28-Aug-2050 01:39:37 GMT; path=/
ROBLOX_HTML_PATH = file:///C:\\Users\\User\\roblox-limiteds-sniper-free\\roblox.html # Your local roblox.html file
```

**Comment by thurdev** [comment]
Probably related to the same other issue that you open, your env looks wrong

**Comment by thurdev** [comment]
Wait until tomorrow, i will create a tutorial

**Comment by WaltDisneyWorld** [comment]
Your env file should **never** have spaces!!

**Comment by CustomAmelia** [comment]
Alright thanks I'll wait for the tutorial

**Comment by thurdev** [comment]
> Your env file should **never** have spaces!!

Wdym? Mine has a lot of spaces

**Comment by thurdev** [comment]
@CustomAmelia can you check the new code now? 
![image](https://user-images.githubusercontent.com/34294813/231997276-730809c7-d49b-429c-a930-b200d9349f8e.png)

**Comment by thurdev** [comment]
Discontinued
