### ISSUE TITLE
wuwu

### ISSUE THREAD

**Issue by mehyu** [thurdev/roblox-limiteds-sniper-free#13]
Can you share the previous code that uses JavaScript/TamperMonkey? 
And also, please add a code if you buy UGC items and they are invalid, it will automatically refresh and allow you to buy them again.

thanks

**Comment by thurdev** [comment]
It already does it, check the branch called tampermonkey

**Comment by mehyu** [comment]
> It already does it, check the branch called tampermonkey

Oh yes, sorry in advance 😅
