### ISSUE TITLE
Don't think Proxies Implementation is functioning correctly

### ISSUE THREAD

**Issue by CustomAmelia** [thurdev/roblox-limiteds-sniper-free#18]
I get Failed to get Items when searching for items (only when using proxies)

Here's my proxies formatting:

    {
        "ip": "",
        "port": "",
        "username": "",
        "password": ""
    },
    
    Please let me know if my format is wrong

**Comment by thurdev** [comment]
Try taking a look at this: https://masteringjs.io/tutorials/axios/proxy

**Comment by CustomAmelia** [comment]
Tried the format there, still didnt work

**Comment by thurdev** [comment]
Whats the error?

**Comment by CustomAmelia** [comment]
> Whats the error?

Failed to get Items when searching for items

**Comment by thurdev** [comment]
I found this text on another repo, maybe this help u 
![image](https://user-images.githubusercontent.com/34294813/232263341-9e5f5404-2a23-4014-96b1-96cac8b8fbb9.png)

**Comment by thurdev** [comment]
Discontinued
