### ISSUE TITLE
I keep getting "Failed to get user!"

### ISSUE THREAD

**Issue by Qi2nR9uw** [thurdev/roblox-limiteds-sniper-free#19]
It will say "Searching for items..." but will soon keep saying "Failed to get user!".

Is there anyway to fix this?

It is also maybe good to note that it does say "Logged in as username" correctly at the top.

A good fix might be to have something in place where if the error happens to relogin the user.

**Comment by DasAleixo** [comment]
hi add me aleixo#7777

**Comment by CustomAmelia** [comment]
Me too

**Comment by thurdev** [comment]
> It will say "Searching for items..." but will soon keep saying "Failed to get user!".
> 
> Is there anyway to fix this?
> 
> It is also maybe good to note that it does say "Logged in as username" correctly at the top.
> 
> A good fix might be to have something in place where if the error happens to relogin the user.

I changed a bit https://github.com/thurdev/roblox-limiteds-sniper-free/pull/20, maybe now will be 1000x faster, and also resolve that problem of not loggin in.

**Comment by Qi2nR9uw** [comment]
> > It will say "Searching for items..." but will soon keep saying "Failed to get user!".
> > Is there anyway to fix this?
> > It is also maybe good to note that it does say "Logged in as username" correctly at the top.
> > A good fix might be to have something in place where if the error happens to relogin the user.
> 
> I changed a bit #20, maybe now will be 1000x faster, and also resolve that problem of not loggin in.

Thank you for the update. Running it now to see if I have any issues.

Also, noob question. If I add an item ID into the json file does it only search for that item or does it still search for everything else that wouldn't be listed in there?

**Comment by CustomAmelia** [comment]
> > > It will say "Searching for items..." but will soon keep saying "Failed to get user!".
> > > Is there anyway to fix this?
> > > It is also maybe good to note that it does say "Logged in as username" correctly at the top.
> > > A good fix might be to have something in place where if the error happens to relogin the user.
> > 
> > 
> > I changed a bit #20, maybe now will be 1000x faster, and also resolve that problem of not loggin in.
> 
> Thank you for the update. Running it now to see if I have any issues.
> 
> Also, noob question. If I add an item ID into the json file does it only search for that item or does it still search for everything else that wouldn't be listed in there?

did the update fix it?

**Comment by Qi2nR9uw** [comment]
> > > > It will say "Searching for items..." but will soon keep saying "Failed to get user!".
> > > > Is there anyway to fix this?
> > > > It is also maybe good to note that it does say "Logged in as username" correctly at the top.
> > > > A good fix might be to have something in place where if the error happens to relogin the user.
> > > 
> > > 
> > > I changed a bit #20, maybe now will be 1000x faster, and also resolve that problem of not loggin in.
> > 
> > 
> > Thank you for the update. Running it now to see if I have any issues.
> > Also, noob question. If I add an item ID into the json file does it only search for that item or does it still search for everything else that wouldn't be listed in there?
> 
> did the update fix it?

So far yes. I've had it running this whole time and no issues so far.

**Comment by Qi2nR9uw** [comment]
Update: I left it going and it completely missed 2 of the free limiteds that came out. It didn't see them at all.

Maybe update is broken? No items were in the items.json file.


After restarting the script it eventually says "Could not get items {"errors":[{"code":0,"message":"InternalServerError"}]}"

**Comment by thurdev** [comment]
Discontinued
