### ISSUE TITLE
new nodejs code

### ISSUE THREAD

**Issue by thurdev** [thurdev/roblox-limiteds-sniper-free#2]
still in tests, better not use for now

**Comment by ghost** [comment]
Will this be like an extension or an app?

**Comment by CustomAmelia** [comment]
How do you format the cookies in the env file?? is it like "", or something else?

**Comment by thurdev** [comment]
> Will this be like an extension or an app?

an app, not sure, run it at your personal computer.



> How do you format the cookies in the env file?? is it like "", or something else?

Just get the cookies from the headers of a request from roblox website, the beginning will look something like that:
![image](https://user-images.githubusercontent.com/34294813/230931359-84db3283-5e91-4314-9ab7-3e83caa12a4c.png)

**Comment by CustomAmelia** [comment]
> > Will this be like an extension or an app?
> 
> an app, not sure, run it at your personal computer.
> 
> > How do you format the cookies in the env file?? is it like "", or something else?
> 
> Just get the cookies from the headers of a request from roblox website, the beginning will look something like that: ![image](https://user-images.githubusercontent.com/34294813/230931359-84db3283-5e91-4314-9ab7-3e83caa12a4c.png)

I still don't understad how I get the headers?

**Comment by CustomAmelia** [comment]
Nvm I figured it out but when I run it for a while I get error : could not get items {"errors":[{"code":0,"message":"Too many requests"}]}

**Comment by thurdev** [comment]
> Nvm I figured it out but when I run it for a while I get error : could not get items {"errors":[{"code":0,"message":"Too many requests"}]}

try to use a bigger timeout :)

you can always add proxies, feel free to.

**Comment by CustomAmelia** [comment]
> > Nvm I figured it out but when I run it for a while I get error : could not get items {"errors":[{"code":0,"message":"Too many requests"}]}
> 
> try to use a bigger timeout :)
> 
> you can always add proxies, feel free to.

How would I add proxies?

**Comment by CustomAmelia** [comment]
I just did some editing of the code myself and I believe I added proxy support

**Comment by thurdev** [comment]
> I just did some editing of the code myself and I believe I added proxy support

nice, if you want feel free to open a pr, i would love that

**Comment by CustomAmelia** [comment]
> > I just did some editing of the code myself and I believe I added proxy support
> 
> nice, if you want feel free to open a pr, i would love that

I failed to do it actually, kept getting errors, could you show me how to or add it?

**Comment by thurdev** [comment]
> > > I just did some editing of the code myself and I believe I added proxy support
> > 
> > 
> > nice, if you want feel free to open a pr, i would love that
> 
> I failed to do it actually, kept getting errors, could you show me how to or add it?

you can do it using curl and adding the parameter to use a proxy, or use the axios which is already present in the code, and do something like this:

```js
const proxy_list = [
    {
        protocol: 'http',
        host: '149.129.239.170',
        port: 8080,
    },
    //...
    {
        protocol: 'http',
        host: '132.129.121.148',
        port: 8080,
    },
    {
        protocol: 'http',
        host: '154.129.98.156',
        port: 8080,
    },
    {
        protocol: 'http',
        host: '211.129.132.150',
        port: 8080,
    },
    {
        protocol: 'http',
        host: '164.129.114.111',
        port: 8080,
    }
]
let random_index = Math.floor(Math.random() * proxy_list.length);

axios.get('https://api.ipify.org/?format=json',
    {
        proxy: proxy_list[random_index]
    }
)
```

**Comment by CustomAmelia** [comment]
> > > > I just did some editing of the code myself and I believe I added proxy support
> > > 
> > > 
> > > nice, if you want feel free to open a pr, i would love that
> > 
> > 
> > I failed to do it actually, kept getting errors, could you show me how to or add it?
> 
> you can do it using curl and adding the parameter to use a proxy, or use the axios which is already present in the code, and do something like this:
> 
> ```js
> const proxy_list = [
>     {
>         protocol: 'http',
>         host: '149.129.239.170',
>         port: 8080,
>     },
>     //...
>     {
>         protocol: 'http',
>         host: '132.129.121.148',
>         port: 8080,
>     },
>     {
>         protocol: 'http',
>         host: '154.129.98.156',
>         port: 8080,
>     },
>     {
>         protocol: 'http',
>         host: '211.129.132.150',
>         port: 8080,
>     },
>     {
>         protocol: 'http',
>         host: '164.129.114.111',
>         port: 8080,
>     }
> ]
> let random_index = Math.floor(Math.random() * proxy_list.length);
> 
> axios.get('https://api.ipify.org/?format=json',
>     {
>         proxy: proxy_list[random_index]
>     }
> )
> ```

I'll try but could you add proxy support integrated?

**Comment by CustomAmelia** [comment]
I tried to do it but was having issues, could you push a proxy update as soon as you can?

**Comment by CustomAmelia** [comment]
Nvm i got it!

**Comment by thurdev** [comment]
> Nvm i got it!

nice, share it if possible, i dont have too much time this week xd

**Comment by CustomAmelia** [comment]
> > Nvm i got it!
> 
> nice, share it if possible, i dont have too much time this week xd

I'll open a pr

**Comment by CustomAmelia** [comment]
> > Nvm i got it!
> 
> nice, share it if possible, i dont have too much time this week xd

do i have to do the pull request in typescript? i compiled the typescript and just used it in javascript and i cant compile it back to typescript

**Comment by thurdev** [comment]
> > > Nvm i got it!
> > 
> > 
> > nice, share it if possible, i dont have too much time this week xd
> 
> do i have to do the pull request in typescript? i compiled the typescript and just used it in javascript and i cant compile it back to typescript

typescript sir, please 🙏 
its pretty simple, just define types, i still gonna improve the script, so if you do it in typescript i will use ur code, if not the code is removed every time it is compiled.

**Comment by CustomAmelia** [comment]
> > > > Nvm i got it!
> > > 
> > > 
> > > nice, share it if possible, i dont have too much time this week xd
> > 
> > 
> > do i have to do the pull request in typescript? i compiled the typescript and just used it in javascript and i cant compile it back to typescript
> 
> typescript sir, please 🙏 its pretty simple, just define types, i still gonna improve the script, so if you do it in typescript i will use ur code, if not the code is removed every time it is compiled.

alright i will try but im sorry if it isn't good or the code is trash

**Comment by thurdev** [comment]
np np, gonna close this issue for now, anything else open a new one 👍
