### ISSUE TITLE
Add an option to only take 1 per limited.

### ISSUE THREAD

**Issue by Qi2nR9uw** [thurdev/roblox-limiteds-sniper-free#21]
I think it would be fair to have an option (set in .env id imagine) where it only will snipe 1 per limited to give everyone a fair chance and not abuse like the others enjoy doing.

**Comment by CustomAmelia** [comment]
No

**Comment by karl-police** [comment]
> I think it would be fair to have an option (set in .env id imagine) where it only will snipe 1 per limited to give everyone a fair chance and not abuse like the others enjoy doing.

I agree that there should be an option for this, in the meantime here's a script that let's you take UGC Items only once, but you gotta run it manually on the page.

https://pastebin.com/ijkU8sDP

I just made that script with the help of this repository as well, I actually found this repository by searching through source code for what I need to put in the arguments for those APIs.


This should definitely be added, an option to only take one.
Also, does this stuff have a price limit? The script I made won't let you purchase unless it's free. If you wanna change that, just uncomment that one part in the code.

**Comment by Qi2nR9uw** [comment]
> > I think it would be fair to have an option (set in .env id imagine) where it only will snipe 1 per limited to give everyone a fair chance and not abuse like the others enjoy doing.
> 
> I agree that there should be an option for this, in the meantime here's a script that let's you take UGC Items only once, but you gotta run it manually on the page.
> 
> https://pastebin.com/ijkU8sDP
> 
> I just made that script with the help of this repository as well, I actually found this repository by searching through source code for what I need to put in the arguments for those APIs.
> 
> This should definitely be added, an option to only take one. Also, does this stuff have a price limit? The script I made won't let you purchase unless it's free. If you wanna change that, just uncomment that one part in the code.

Ill be sure to check it out. This script has no limit. I lost 2000 robux because of it. I haven't gotten a single free item from this script.

A script that auto searches for free items instead would be amazing. No need to provide IDs or miss out.

**Comment by karl-police** [comment]
> > > I think it would be fair to have an option (set in .env id imagine) where it only will snipe 1 per limited to give everyone a fair chance and not abuse like the others enjoy doing.
> > 
> > 
> > I agree that there should be an option for this, in the meantime here's a script that let's you take UGC Items only once, but you gotta run it manually on the page.
> > https://pastebin.com/ijkU8sDP
> > I just made that script with the help of this repository as well, I actually found this repository by searching through source code for what I need to put in the arguments for those APIs.
> > This should definitely be added, an option to only take one. Also, does this stuff have a price limit? The script I made won't let you purchase unless it's free. If you wanna change that, just uncomment that one part in the code.
> 
> Ill be sure to check it out. This script has no limit. I lost 2000 robux because of it. I haven't gotten a single free item from this script.
> 
> A script that auto searches for free items instead would be amazing. No need to provide IDs or miss out.

I could modify this repository, by forking it.


Though idk about yarn, you used this thing. How easy is it to install yarn, and how easy is it to remove?

**Comment by thurdev** [comment]
> > > I think it would be fair to have an option (set in .env id imagine) where it only will snipe 1 per limited to give everyone a fair chance and not abuse like the others enjoy doing.
> > 
> > 
> > I agree that there should be an option for this, in the meantime here's a script that let's you take UGC Items only once, but you gotta run it manually on the page.
> > https://pastebin.com/ijkU8sDP
> > I just made that script with the help of this repository as well, I actually found this repository by searching through source code for what I need to put in the arguments for those APIs.
> > This should definitely be added, an option to only take one. Also, does this stuff have a price limit? The script I made won't let you purchase unless it's free. If you wanna change that, just uncomment that one part in the code.
> 
> @Qi2nR9uw
> Ill be sure to check it out. This script has no limit. I lost 2000 robux because of it. I haven't gotten a single free item from this script.
> 
> A script that auto searches for free items instead would be amazing. No need to provide IDs or miss out.

Probably you must have changed something, because if you had read the code you would know that this function: https://github.com/thurdev/roblox-limiteds-sniper-free/blob/fc84d5fde2328fbcb42335b91a0eadc9eae04280/src/utils/preparedRequests.ts#L25-L27 has there are 2 parameters max price and min price, setting both to 0, it will never buy you anything above that value.

**Comment by thurdev** [comment]
> > > > I think it would be fair to have an option (set in .env id imagine) where it only will snipe 1 per limited to give everyone a fair chance and not abuse like the others enjoy doing.
> > > 
> > > 
> > > I agree that there should be an option for this, in the meantime here's a script that let's you take UGC Items only once, but you gotta run it manually on the page.
> > > https://pastebin.com/ijkU8sDP
> > > I just made that script with the help of this repository as well, I actually found this repository by searching through source code for what I need to put in the arguments for those APIs.
> > > This should definitely be added, an option to only take one. Also, does this stuff have a price limit? The script I made won't let you purchase unless it's free. If you wanna change that, just uncomment that one part in the code.
> > 
> > 
> > Ill be sure to check it out. This script has no limit. I lost 2000 robux because of it. I haven't gotten a single free item from this script.
> > A script that auto searches for free items instead would be amazing. No need to provide IDs or miss out.
> 
> @karl-police 
> I could modify this repository, by forking it.
> 
> Though idk about yarn, you used this thing. How easy is it to install yarn, and how easy is it to remove?

Its really similar to npm, but instead its yarn, example:

```bash
$    npm install express
$    yarn add express
```
After using yarn for a while, I noticed that it has fewer errors in package installations than npm.

**Comment by thurdev** [comment]
Discontinued
