### ISSUE TITLE
Add an option where it will only buy items if they're free

### ISSUE THREAD

**Issue by Qi2nR9uw** [thurdev/roblox-limiteds-sniper-free#22]
I just lost 2000 robux due to it buying since there are no systems in place for this.

**Comment by karl-police** [comment]
> I just lost 2000 robux due to it buying since there are no systems in place for this.

fork repository

change ``expectedPrice`` to ``0``, cuz it will throw PriceMismatch error


I haven't done that yet cuz idk what the hell yarn is

**Comment by Qi2nR9uw** [comment]
> > I just lost 2000 robux due to it buying since there are no systems in place for this.
> 
> fork repository
> 
> change `expectedPrice` to `0`, cuz it will throw PriceMismatch error
> 
> I haven't done that yet cuz idk what the hell yarn is

Yeah, the installation instructions for this script is a bit strange. Here is a better one that may help:

1. Install Git: Go to https://git-scm.com/downloads and download and install Git for Windows.
2. Install Node.js: Go to https://nodejs.org/en/ and download and install
3. Install Yarn: Type "npm install --global yarn" in the Command Prompt and press Enter. This command will install Yarn globally on your system.
4. Open Command Prompt: Press the Windows key and type "Command Prompt" and press Enter.
5. Clone the repository: Type "git clone https://github.com/thurdev/roblox-limiteds-sniper-free.git" in the Command Prompt and press Enter.
6. Go into the repository: Type "cd roblox-limiteds-sniper-free" in the Command Prompt and press Enter.
7. Install dependencies: Type "yarn install" in the Command Prompt and press Enter.
8. Setup .env: Type "copy .env.example .env" in the Command Prompt and press Enter. Then follow the tutorial to set up the .env file.
9. Run the app: Type "yarn start" in the Command Prompt and press Enter. The app should start running.

**Comment by karl-police** [comment]
> > > I just lost 2000 robux due to it buying since there are no systems in place for this.
> > 
> > 
> > fork repository
> > change `expectedPrice` to `0`, cuz it will throw PriceMismatch error
> > I haven't done that yet cuz idk what the hell yarn is
> 
> Yeah, the installation instructions for this script is a bit strange. Here is a better one that may help:
> 
> 1. Install Git: Go to https://git-scm.com/downloads and download and install Git for Windows.
> 2. Install Node.js: Go to https://nodejs.org/en/ and download and install
> 3. Install Yarn: Type "npm install --global yarn" in the Command Prompt and press Enter. This command will install Yarn globally on your system.
> 4. Open Command Prompt: Press the Windows key and type "Command Prompt" and press Enter.
> 5. Clone the repository: Type "git clone https://github.com/thurdev/roblox-limiteds-sniper-free.git" in the Command Prompt and press Enter.
> 6. Go into the repository: Type "cd roblox-limiteds-sniper-free" in the Command Prompt and press Enter.
> 7. Install dependencies: Type "yarn install" in the Command Prompt and press Enter.
> 8. Setup .env: Type "copy .env.example .env" in the Command Prompt and press Enter. Then follow the tutorial to set up the .env file.
> 9. Run the app: Type "yarn start" in the Command Prompt and press Enter. The app should start running.

there's this one too

https://github.com/Furrycality/UGCatcher

**Comment by thurdev** [comment]
I already gave up on this project, since there is a lot on the market, much better for example: Xolo, or Wagoogous (Which will likely terminate your services as well).
