### ISSUE TITLE
Question what happens at buy() and buyItem() even when the purchase fails, out of curiousity?

### ISSUE THREAD

**Issue by karl-police** [thurdev/roblox-limiteds-sniper-free#26]
What happens at buy() and buyItem() even when the purchase fails, out of curiousity?

@thurdev

ChatGPT has been making things up... uhhh

but yeah I don't think there's retry logic, is there?

**Comment by thurdev** [comment]
> @karl-police 
> What happens at buy() and buyItem() even when the purchase fails, out of curiousity?
> 
> @thurdev
> 
> ChatGPT has been making things up... uhhh
> 
> but yeah I don't think there's retry logic, is there?

Well, I don't remember too much, but he skips if he can't buy it, and goes back to the loop to get free items, if the item still there, he tries again.
