### ISSUE TITLE
Proxy Enhancement

### ISSUE THREAD

**Issue by CustomAmelia** [thurdev/roblox-limiteds-sniper-free#7]
Make axios use the same proxy until it gets an error of too many requests, then switch to a different random one. Would improve it a lot

**Comment by thurdev** [comment]
btw @CustomAmelia which provider of proxies u are using?

**Comment by CustomAmelia** [comment]
> btw @CustomAmelia which provider of proxies u are using?

webshare free trial

**Comment by thurdev** [comment]
Discontinued
